from django.urls import path

from .views import (
    AccountCenterView,
    AnnouncementDetailView,
    CheckoutView,
    CreateOrderView,
    GuestOrderLookupView,
    HealthView,
    HelpArticleDetailView,
    HelpCenterView,
    MerchantDashboardView,
    MerchantInventoryView,
    MerchantOrderDetailView,
    MerchantOrderListView,
    MerchantProductCreateView,
    MerchantProductListView,
    MerchantProductUpdateView,
    MockPaymentView,
    OrderDetailView,
    PaymentCancelView,
    PaymentSuccessView,
    ProductDetailView,
    StartPaymentView,
    StorefrontView,
    StripeWebhookView,
)

urlpatterns = [
    path("", StorefrontView.as_view(), name="storefront"),
    path("health/", HealthView.as_view(), name="health"),
    path("announcements/<int:pk>/", AnnouncementDetailView.as_view(), name="announcement_detail"),
    path("help/", HelpCenterView.as_view(), name="help_center"),
    path("help/<slug:slug>/", HelpArticleDetailView.as_view(), name="help_article_detail"),
    path("order-lookup/", GuestOrderLookupView.as_view(), name="order_lookup"),
    path("dashboard/", MerchantDashboardView.as_view(), name="merchant_dashboard"),
    path("dashboard/products/", MerchantProductListView.as_view(), name="merchant_products"),
    path("dashboard/products/new/", MerchantProductCreateView.as_view(), name="merchant_product_create"),
    path("dashboard/products/<int:pk>/edit/", MerchantProductUpdateView.as_view(), name="merchant_product_edit"),
    path("dashboard/inventory/", MerchantInventoryView.as_view(), name="merchant_inventory"),
    path("dashboard/orders/", MerchantOrderListView.as_view(), name="merchant_orders"),
    path("dashboard/orders/<slug:order_no>/", MerchantOrderDetailView.as_view(), name="merchant_order_detail"),
    path("me/", AccountCenterView.as_view(), name="account_center"),
    path("products/<slug:slug>/", ProductDetailView.as_view(), name="product_detail"),
    path("products/<slug:slug>/buy/", CreateOrderView.as_view(), name="create_order"),
    path("orders/<slug:order_no>/checkout/", CheckoutView.as_view(), name="checkout"),
    path("orders/<slug:order_no>/pay/", StartPaymentView.as_view(), name="start_payment"),
    path("orders/<slug:order_no>/mock-pay/", MockPaymentView.as_view(), name="mock_pay"),
    path("orders/<slug:order_no>/success/", PaymentSuccessView.as_view(), name="payment_success"),
    path("orders/<slug:order_no>/cancel/", PaymentCancelView.as_view(), name="payment_cancel"),
    path("orders/<slug:order_no>/", OrderDetailView.as_view(), name="order_detail"),
    path("webhooks/stripe/", StripeWebhookView.as_view(), name="stripe_webhook"),
]
