# Generated by Django 5.2.12 on 2026-03-21 18:27

import django.db.models.deletion
import shop.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('title', models.CharField(max_length=120, verbose_name='商品名称')),
                ('slug', models.SlugField(unique=True, verbose_name='链接标识')),
                ('summary', models.CharField(max_length=180, verbose_name='摘要')),
                ('description', models.TextField(verbose_name='商品详情')),
                ('cover_url', models.URLField(blank=True, verbose_name='封面图链接')),
                ('face_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='面值')),
                ('token_amount', models.PositiveIntegerField(default=0, verbose_name='Token 数量')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='售价')),
                ('delivery_method', models.CharField(choices=[('stock_card', '库存卡密'), ('partner_api', '合作 API')], default='stock_card', max_length=20, verbose_name='供货方式')),
                ('provider_sku', models.CharField(blank=True, max_length=80, verbose_name='合作方 SKU')),
                ('badge', models.CharField(blank=True, max_length=40, verbose_name='角标文案')),
                ('is_active', models.BooleanField(default=True, verbose_name='上架中')),
                ('is_featured', models.BooleanField(default=True, verbose_name='首页推荐')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
                'ordering': ('-is_featured', 'price'),
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('order_no', models.CharField(default=shop.models.generate_order_no, max_length=32, unique=True, verbose_name='订单号')),
                ('status', models.CharField(choices=[('pending_payment', '待支付'), ('paid', '已支付'), ('fulfilling', '发货中'), ('completed', '已完成'), ('failed', '失败'), ('cancelled', '已取消')], default='pending_payment', max_length=30, verbose_name='订单状态')),
                ('payment_status', models.CharField(choices=[('unpaid', '未支付'), ('checkout_created', '支付链接已创建'), ('paid', '支付成功'), ('refunded', '已退款')], default='unpaid', max_length=30, verbose_name='支付状态')),
                ('payment_provider', models.CharField(blank=True, max_length=40, verbose_name='支付渠道')),
                ('payment_reference', models.CharField(blank=True, max_length=120, verbose_name='支付流水')),
                ('checkout_url', models.URLField(blank=True, verbose_name='支付链接')),
                ('customer_note', models.CharField(blank=True, max_length=240, verbose_name='买家备注')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='小计')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='应付金额')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
                ('fulfilled_at', models.DateTimeField(blank=True, null=True, verbose_name='发货时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('product_title', models.CharField(max_length=120, verbose_name='下单商品名')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='数量')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='单价')),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='行金额')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='shop.product')),
            ],
            options={
                'verbose_name': '订单明细',
                'verbose_name_plural': '订单明细',
            },
        ),
        migrations.CreateModel(
            name='DeliveryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('source', models.CharField(choices=[('stock', '库存卡密'), ('api', '合作 API')], max_length=20, verbose_name='来源')),
                ('display_code', models.CharField(max_length=255, verbose_name='交付内容')),
                ('supplier_payload', models.JSONField(blank=True, default=dict, verbose_name='供应商返回')),
                ('delivered_at', models.DateTimeField(auto_now_add=True, verbose_name='交付时间')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='shop.orderitem')),
            ],
            options={
                'verbose_name': '发货记录',
                'verbose_name_plural': '发货记录',
            },
        ),
        migrations.CreateModel(
            name='PaymentAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('provider', models.CharField(max_length=40, verbose_name='支付平台')),
                ('reference', models.CharField(max_length=120, verbose_name='平台流水')),
                ('checkout_url', models.URLField(blank=True, verbose_name='支付跳转')),
                ('status', models.CharField(choices=[('created', '已创建'), ('paid', '已支付'), ('failed', '失败')], default='created', max_length=20, verbose_name='状态')),
                ('raw_payload', models.JSONField(blank=True, default=dict, verbose_name='原始数据')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_attempts', to='shop.order')),
            ],
            options={
                'verbose_name': '支付记录',
                'verbose_name_plural': '支付记录',
            },
        ),
        migrations.CreateModel(
            name='CardCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('code', models.CharField(max_length=255, unique=True, verbose_name='卡密内容')),
                ('note', models.CharField(blank=True, max_length=120, verbose_name='备注')),
                ('status', models.CharField(choices=[('available', '可售'), ('sold', '已售')], default='available', max_length=20, verbose_name='状态')),
                ('sold_at', models.DateTimeField(blank=True, null=True, verbose_name='售出时间')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_codes', to='shop.product')),
            ],
            options={
                'verbose_name': '卡密库存',
                'verbose_name_plural': '卡密库存',
                'ordering': ('product', 'status', '-created_at'),
            },
        ),
    ]
