# Generated by Django 5.2.12 on 2026-03-22 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='分类名称')),
                ('slug', models.SlugField(unique=True, verbose_name='分类标识')),
                ('summary', models.CharField(blank=True, max_length=180, verbose_name='分类说明')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用中')),
            ],
            options={
                'verbose_name': '商品分类',
                'verbose_name_plural': '商品分类',
                'ordering': ('sort_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='SiteAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('title', models.CharField(max_length=120, verbose_name='公告标题')),
                ('body', models.TextField(verbose_name='公告内容')),
                ('link_url', models.URLField(blank=True, verbose_name='跳转链接')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用中')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='置顶')),
            ],
            options={
                'verbose_name': '站点公告',
                'verbose_name_plural': '站点公告',
                'ordering': ('-is_pinned', 'sort_order', '-created_at'),
            },
        ),
        migrations.AddField(
            model_name='order',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='查询邮箱'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='shop.productcategory', verbose_name='商品分类'),
        ),
    ]
