# Generated by Django 5.2.12 on 2026-03-22 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_productcategory_siteannouncement_order_contact_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('title', models.CharField(max_length=140, verbose_name='文章标题')),
                ('slug', models.SlugField(unique=True, verbose_name='文章标识')),
                ('section', models.CharField(choices=[('guide', '新手教程'), ('faq', '常见问题'), ('aftersale', '售后说明'), ('api', '接口对接')], default='guide', max_length=20, verbose_name='文章栏目')),
                ('summary', models.CharField(max_length=200, verbose_name='文章摘要')),
                ('content', models.TextField(verbose_name='正文内容')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('is_published', models.BooleanField(default=True, verbose_name='已发布')),
                ('is_featured', models.BooleanField(default=False, verbose_name='首页展示')),
            ],
            options={
                'verbose_name': '帮助文章',
                'verbose_name_plural': '帮助文章',
                'ordering': ('section', 'sort_order', '-created_at'),
            },
        ),
    ]
