# Generated by Django 5.2.12 on 2026-03-23 08:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_helparticle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='merchant_note',
            field=models.CharField(blank=True, max_length=240, verbose_name='商家备注'),
        ),
        migrations.AddField(
            model_name='product',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(default=3, verbose_name='低库存提醒阈值'),
        ),
        migrations.CreateModel(
            name='InventoryImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('note', models.CharField(blank=True, max_length=120, verbose_name='备注')),
                ('total_submitted', models.PositiveIntegerField(default=0, verbose_name='提交数量')),
                ('imported_count', models.PositiveIntegerField(default=0, verbose_name='成功导入')),
                ('duplicate_count', models.PositiveIntegerField(default=0, verbose_name='重复数量')),
                ('duplicate_sample', models.TextField(blank=True, verbose_name='重复样例')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_import_batches', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_batches', to='shop.product')),
            ],
            options={
                'verbose_name': '库存导入批次',
                'verbose_name_plural': '库存导入批次',
                'ordering': ('-created_at',),
            },
        ),
    ]
