# Generated by Django 5.2.12 on 2026-03-27 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_supportticket_supportticketmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='checkout_url',
            field=models.URLField(blank=True, max_length=2048, verbose_name='支付链接'),
        ),
        migrations.AlterField(
            model_name='paymentattempt',
            name='checkout_url',
            field=models.URLField(blank=True, max_length=2048, verbose_name='支付跳转'),
        ),
    ]
